<?php

return array(
    'defaultController' => 'index',
    'language' => 'ru',
    'sourceLanguage' => 'ru',
    'timeZone' => 'UTC',
    'import' => array(
        'application.models.*',
        'application.components.*',
    ),
    'components' => array(
        'urlManager' => array(
            'class' => 'application.components.UrlManager',
            'urlFormat' => 'path',
            'showScriptName' => false,
            'rules' => array(
                '<language:(ru|uk)>' => 'index/index',
                '<language:(ru|uk)>/about' => 'about/index',
                '<language:(ru|uk)>/brand' => 'brand/index',
                '<language:(ru|uk)>/catalog/<id>' => 'catalog/index',
                '<language:(ru|uk)>/catalog' => 'catalog/index',
                '<language:(ru|uk)>/contact' => 'contact/index',
                '<language:(ru|uk)>/donor' => 'donor/index',
                '<language:(ru|uk)>/login' => 'site/login',
                '<language:(ru|uk)>/news/<id>-category' => 'news/index',
                '<language:(ru|uk)>/news/<id>' => 'news/view',
                '<language:(ru|uk)>/news/' => 'news/index',
                '<language:(ru|uk)>/specialist' => 'newscategory/index',
                '<language:(ru|uk)>/product/<id>' => 'product/view',
                '<language:(ru|uk)>/profile' => 'profile/index',
                '<language:(ru|uk)>/review' => 'review/index',
                '<language:(ru|uk)>/signup' => 'site/signup',
                '' => 'index/index',
                'about' => 'about/index',
                'brand' => 'brand/index',
                'catalog/<id>' => 'catalog/index',
                'catalog' => 'catalog/index',
                'contact' => 'contact/index',
                'donor' => 'donor/index',
                'login' => 'site/login',
                'specialist' => 'newscategory/index',
                'news/<id>-category' => 'news/index',
                'news/<id>' => 'news/view',
                'news' => 'news/index',
                'product/<id>' => 'product/view',
                'profile' => 'profile/index',
                'review/check' => 'review/check',
                'review/more' => 'review/more',
                'review' => 'review/index',
                'search' => 'search/index',
                'signup' => 'site/signup',
                '<language:(ru|uk)>/<controller>/<action>/<id>' => '<controller>/<action>',
                '<language:(ru|uk)>/<controller>/<action>' => '<controller>/<action>',
                '<language:(ru|uk)>/<controller>' => '<controller>/index',
                '<module:(admin)>/<language:(ru|uk)>/<controller>/<action>/<id>' => '<module>/<controller>/<action>',
                '<module:(admin)>/<language:(ru|uk)>/<controller>/<action>' => '<module>/<controller>/<action>',
                '<module:(admin)>/<language:(ru|uk)>/<controller>' => '<module>/<controller>',
                '<module:(admin)>/<language:(ru|uk)>' => '<module>/index',
                '<module:(admin)>/<controller>/<action>/<id>' => '<module>/<controller>/<action>',
                '<module:(admin)>/<controller>/<action>' => '<module>/<controller>/<action>',
                '<module:(admin)>/<controller>' => '<module>/<controller>',
                '<module:(admin)>' => '<module>/index',
            ),
        ),
        'db' => array(
            'connectionString' => 'mysql:host=localhost;dbname=motulm00_redmed',
            'emulatePrepare' => true,
            'username' => 'motulm00_redmed',
            'password' => 'jhsVyBI9pq',
            'charset' => 'utf8',
        ),
        'messages' => array(
            'class' => 'CDbMessageSource',
            'cacheID' => 'cache',
            'cachingDuration' => 43200,
            'connectionID' => 'db',
            'sourceMessageTable' => 'i18n_source_messages',
            'translatedMessageTable' => 'i18n_translated_messages',
            'forceTranslation' => true,
        ),
        'user' => array(
            'loginUrl' => array('site/login'),
        ),
    ),
    'modules' => array(
        'admin',
        'gii' => array(
            'class' => 'system.gii.GiiModule',
            'password' => '123',
        ),
    ),
);